### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by bjoernalbers** [drbig/fx-tftp#5]
Hello Piotr,

fx-tftp is my first choice as tftp server, mainly for file transfers to and from different Cisco firewalls.
However, its strong point is - for my understanding - the use as adhoc server and I think the UI should emphasis this.
Here is a draft for version 1.n:

```
$ tftpd
Usage: tftpd [OPTIONS] DIR
    -v, --verbose                    Enable verbose output
    -l, --listen ADDRESS             On which address to listen (default: 0.0.0.0)
    -p, --port PORT                  Serving root directory (default: 69)
    -r, --read-only                  Do not Overwrite existing files (not enabled by default)
```

Some explanations:
- Port and address are common (unsecure) defaults but thats expected behaviour.
- Verbose logging should include a list of files that will be served and which one are currently transferred (+ status)
- Read-only mode should only be optional. Most of the time I overwrite config-files on the fx-tftp side.
- Running on UDP69 requires root priviledges of course so a friendly error message should give a proper hint.

Before I send (possibly unwanted) pull requests I'd like to hear your opinion on this :-)

Greetins from germany,
Björn

**Comment by drbig** [comment]
Hello Björn,

Lemme summarise my opinion:
1. Given you seems to have tested it I'm OK with having 1.0 release
2. Parametrized options should definitely print their defaults
3. I'm OK with changing the defaults
   - Replace current `--overwrite` with perhaps `-p, --preserve Disable overwriting of existing files` (so it's not confused with `--mode`)
   - Some better phrasing for `--mode` still
4. For logging:
   - Without options only general info (connects/disconnects, file uploaded/downloaded)
   - With verbose add progress indicators (note: this has to work sanely with logging to file)
   - If `debug` is needed - well, whatever's useful and not already covered with verbose (and also has to work with output to file)
5. After some thinking I'm even OK with having `DIR` as the required arg rather than `PORT`, though that's the most "controversial" part of your proposal for me :)

I think I can see your general theme of the UI improvements and I agree. Feel free to PR whenever you have something that you like (and have tested :)).

**Comment by bjoernalbers** [comment]
Cool! :+1: 

But I think the most controversial part (which I haven't mentioned yet) is this: we drop everything else, that does not belong in an ad hoc tftp server.

That is:
- no more logging to file
- no more mode selection
- lets even get rid of the "read-only"
- no forking

Why? To be honest: If the build-in "BSD tftdp" on Mac OS X would be more user-friendly I would stick with it.
It runs faster and has a mature (or at least old) codebase.
But its a pain in the ass to use it with different directories.
That's why fx-tftp is the better ad-hoc server.

Also only networking guys will probably use tftp to update their equiptment.
But when someone controls both ends of the connection, then restricting write or read access is in the way.
It actually makes thinks more complicated than they should be.
fx-tftp should be as simple as possible.

The same goes with progress.
Its nice to see a progress bar but most clients do this already.
What would my life a bit easier is to see is a list of files that will actually be shared.

I'll send some code to explain further...

PS: No worries if you find these changes to drastic or if you want move the project in this direction. I could totally understand this. Then I would leave them just in my fork :-)

**Comment by bjoernalbers** [comment]
Hey Piotr,

I realized that it's better to move my changes in a separate gem rather than trying to change your whole server.
Again, no worries :-)

Björn

**Comment by drbig** [comment]
Sure :) Though if by any chance you PR the UI changes as per my five point list (or some subset) I'll gladly merge.

**Comment by drbig** [comment]
Oh you did PR... sorry haven't even seen it... Proceed as you wish in any case!
